# Generated by Django 2.1.2 on 2019-11-20 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discountplace', '0003_auto_20191120_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritePlace',
            new_name='FavoriteLocation',
        ),
    ]
