# Generated by Django 2.1.2 on 2019-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0005_auto_20191120_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelocation',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
