# Generated by Django 2.1.2 on 2019-11-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0007_placerequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placerequest',
            name='registration_num',
        ),
    ]
