# Generated by Django 2.1.2 on 2019-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0008_remove_placerequest_registration_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placerequest',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
