# Generated by Django 2.1.2 on 2019-11-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0010_auto_20191120_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placerequest',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discountplace.Place'),
        ),
    ]
