# Generated by Django 2.2.7 on 2019-12-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0011_auto_20191120_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='favoritelocation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
