# Generated by Django 2.2.7 on 2019-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0012_auto_20191205_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
