# Generated by Django 2.2.7 on 2019-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0013_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duty_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
