# Generated by Django 2.2.7 on 2019-12-07 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0014_auto_20191207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duty_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 15, 2, 15, 993098, tzinfo=utc)),
        ),
    ]
