# Generated by Django 2.2.7 on 2019-12-07 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discountplace', '0015_auto_20191207_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='duty_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 15, 5, 13, 312954, tzinfo=utc)),
        ),
    ]
